local group = BodyLocations.getGroup("Human")
  group:getOrCreateLocation("Transmog_OutfitBagOne")
  group:getOrCreateLocation("Transmog_OutfitBagTwo")
  group:getOrCreateLocation("Transmog_Cosmetic")
  group:setMultiItem("Transmog_Cosmetic", true)